// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelLink() {
  return window['go']['main']['App']['CancelLink']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetNetwork() {
  return window['go']['main']['App']['GetNetwork']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function LinkStatus() {
  return window['go']['main']['App']['LinkStatus']();
}

export function StartLink() {
  return window['go']['main']['App']['StartLink']();
}

export function StartService() {
  return window['go']['main']['App']['StartService']();
}

export function StopService() {
  return window['go']['main']['App']['StopService']();
}

export function TailLogs() {
  return window['go']['main']['App']['TailLogs']();
}

export function Unlink() {
  return window['go']['main']['App']['Unlink']();
}
