// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetNetwork():Promise<main.NetworkResponse>;

export function GetStatus():Promise<main.StatusResponse>;

export function LinkStatus():Promise<main.LinkStatusResponse>;

export function StartLink():Promise<main.LinkStartResponse>;

export function StartService():Promise<main.LinkStatusResponse>;

export function StopService():Promise<main.LinkStatusResponse>;

export function TailLogs():Promise<main.LogsResponse>;

export function Unlink():Promise<main.LinkStatusResponse>;
